dist: xenial

language: cpp

compiler:
# GCC 7.3.0 works locally, but I can't get Travis's old stuff to work.
#  - gcc
  - clang

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/test"
    packages:
      - clang-5.0
      - clang-format-5.0
      - g++-8
      - libstdc++-8-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
#  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
#  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
#  - g++ --version
  - make VERBOSE=1
  - cd ..
  - ./run-clang-format.py -r src
